angle_min: -0.785398
angle_max: 0.785398
laser_transform:
  # Rotation from laser to IMU
  orientation:
    w: -0.5
    x: -0.5
    y: -0.5
    z: 0.5
  # Position of laser in IMU frame
  position:
    x: 0.0
    y: 0.0
    z: 0.0
